-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2018-07-25 17:15:29 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE dashedpost (
    user_username   VARCHAR2(20) NOT NULL,
    post_postid     INTEGER NOT NULL
);

ALTER TABLE dashedpost ADD CONSTRAINT dashedpost_pk PRIMARY KEY ( user_username,
                                                                  post_postid );

CREATE TABLE flaggedpost (
    user_username   VARCHAR2(20) NOT NULL,
    post_postid     INTEGER NOT NULL
);

ALTER TABLE flaggedpost ADD CONSTRAINT flaggedpost_pk PRIMARY KEY ( user_username,
                                                                    post_postid );

CREATE TABLE post (
    postid          INTEGER NOT NULL,
    user_username   VARCHAR2(20) NOT NULL,
    text            VARCHAR2(500),
    image           BLOB,
    topic_topicid   INTEGER NOT NULL,
    post_postid     INTEGER NOT NULL
);

ALTER TABLE post ADD CONSTRAINT post_pk PRIMARY KEY ( postid );

CREATE TABLE topic (
    topicid     INTEGER NOT NULL,
    topicname   VARCHAR2(50) NOT NULL
);

ALTER TABLE topic ADD CONSTRAINT topic_pk PRIMARY KEY ( topicid );

CREATE TABLE "user" (
    username    VARCHAR2(20) NOT NULL,
    password    VARCHAR2(20) NOT NULL,
    email       VARCHAR2(50) NOT NULL,
    firstname   VARCHAR2(20) NOT NULL,
    lastname    VARCHAR2(20)
);

ALTER TABLE "user" ADD CONSTRAINT user_pk PRIMARY KEY ( username );

ALTER TABLE dashedpost
    ADD CONSTRAINT dashedpost_post_fk FOREIGN KEY ( post_postid )
        REFERENCES post ( postid );

ALTER TABLE dashedpost
    ADD CONSTRAINT dashedpost_user_fk FOREIGN KEY ( user_username )
        REFERENCES "user" ( username );

ALTER TABLE flaggedpost
    ADD CONSTRAINT flaggedpost_post_fk FOREIGN KEY ( post_postid )
        REFERENCES post ( postid );

ALTER TABLE flaggedpost
    ADD CONSTRAINT flaggedpost_user_fk FOREIGN KEY ( user_username )
        REFERENCES "user" ( username );

ALTER TABLE post
    ADD CONSTRAINT post_post_fk FOREIGN KEY ( post_postid )
        REFERENCES post ( postid );

ALTER TABLE post
    ADD CONSTRAINT post_topic_fk FOREIGN KEY ( topic_topicid )
        REFERENCES topic ( topicid );

ALTER TABLE post
    ADD CONSTRAINT post_user_fk FOREIGN KEY ( user_username )
        REFERENCES "user" ( username );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
